### Crear usuario (registro público)
POST http://localhost:8000/api/register
Content-Type: application/json

{
  "nickname": "ramon3g",
  "name": "Jesús",
  "lastname": "González",
  "email": "pedroo0@example.com",
  "password": "12345678",
  "birthdate": "2003-05-12",
  "profile_image_url": null
}

### Login para obtener token
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password"
}

### Logout (necesita token)
POST http://localhost:8000/api/logout
Authorization: Bearer 1|QhUo6PyGuvM6wgWoz8M0IUvBRwkILnYEYKFzGAh3a7a4e2fc
### Guardar token que devuelve el login (copia lo que te devuelva)
# token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsInR...

### Listar usuarios (solo admin)
GET http://localhost:8000/api/users
Authorization: Bearer 2|qa9PnlQrujyfLd3NsqkSbpAXPWyWP5PVnlhgAsZa7b7c52c1

### Consultar un usuario
GET http://localhost:8000/api/users/1
Authorization: Bearer 5|j2WrsroEvHKyomERjLDU33rHybb89OnOjC2RyvEy57c9e6e4

### Actualizar usuario
PUT http://localhost:8000/api/users/2
Authorization: Bearer 2|qa9PnlQrujyfLd3NsqkSbpAXPWyWP5PVnlhgAsZa7b7c52c1
Content-Type: application/json

{
  "nickname": "jesus3g",
  "name": "Jesús",
  "lastname": "González",
  "email": "jesus@example.com",
  "password": "12345678",
  "birthdate": "2003-05-12",
  "profile_image_url": null
}

### Eliminar usuario
DELETE http://localhost:8000/api/users/1
Authorization: Bearer 2|qa9PnlQrujyfLd3NsqkSbpAXPWyWP5PVnlhgAsZa7b7c52c1

### Asignar roles a un usuario (solo admin)
POST http://localhost:8000/api/users/1/roles
Authorization: Bearer 1|1ZQQo9lob3qVNJ8lCD6UR9iZLcVlO0xuaKpJ1iP6c417d5e6
Content-Type: application/json

{
  "roles": 3
}


